package com.drools.example;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NotificationOutput implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "alert1")
	private java.lang.String alert1;
	@org.kie.api.definition.type.Label(value = "alert2")
	private java.lang.String alert2;
	@org.kie.api.definition.type.Label(value = "alert3")
	private java.lang.String alert3;
	@org.kie.api.definition.type.Label(value = "alert4")
	private java.lang.String alert4;
	@org.kie.api.definition.type.Label(value = "alert5")
	private java.lang.String alert5;
	@org.kie.api.definition.type.Label(value = "alert6")
	private java.lang.String alert6;

	public NotificationOutput() {
	}

	public java.lang.String getAlert1() {
		return this.alert1;
	}

	public void setAlert1(java.lang.String alert1) {
		this.alert1 = alert1;
	}

	public java.lang.String getAlert2() {
		return this.alert2;
	}

	public void setAlert2(java.lang.String alert2) {
		this.alert2 = alert2;
	}

	public java.lang.String getAlert3() {
		return this.alert3;
	}

	public void setAlert3(java.lang.String alert3) {
		this.alert3 = alert3;
	}

	public java.lang.String getAlert4() {
		return this.alert4;
	}

	public void setAlert4(java.lang.String alert4) {
		this.alert4 = alert4;
	}

	public java.lang.String getAlert5() {
		return this.alert5;
	}

	public void setAlert5(java.lang.String alert5) {
		this.alert5 = alert5;
	}

	public java.lang.String getAlert6() {
		return this.alert6;
	}

	public void setAlert6(java.lang.String alert6) {
		this.alert6 = alert6;
	}

	public NotificationOutput(java.lang.String alert1, java.lang.String alert2,
			java.lang.String alert3, java.lang.String alert4,
			java.lang.String alert5, java.lang.String alert6) {
		this.alert1 = alert1;
		this.alert2 = alert2;
		this.alert3 = alert3;
		this.alert4 = alert4;
		this.alert5 = alert5;
		this.alert6 = alert6;
	}

}