package com.drools.example;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Notification implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "id")
	private java.lang.String id;
	@org.kie.api.definition.type.Label(value = "attr1")
	private java.lang.String attr1;
	@org.kie.api.definition.type.Label(value = "attr2")
	private java.lang.String attr2;
	@org.kie.api.definition.type.Label(value = "attr3")
	private java.lang.String attr3;
	@org.kie.api.definition.type.Label(value = "attr4")
	private java.lang.String attr4;
	@org.kie.api.definition.type.Label(value = "attr5")
	private java.lang.String attr5;

	public Notification() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getAttr1() {
		return this.attr1;
	}

	public void setAttr1(java.lang.String attr1) {
		this.attr1 = attr1;
	}

	public java.lang.String getAttr2() {
		return this.attr2;
	}

	public void setAttr2(java.lang.String attr2) {
		this.attr2 = attr2;
	}

	public java.lang.String getAttr3() {
		return this.attr3;
	}

	public void setAttr3(java.lang.String attr3) {
		this.attr3 = attr3;
	}

	public java.lang.String getAttr4() {
		return this.attr4;
	}

	public void setAttr4(java.lang.String attr4) {
		this.attr4 = attr4;
	}

	public java.lang.String getAttr5() {
		return this.attr5;
	}

	public void setAttr5(java.lang.String attr5) {
		this.attr5 = attr5;
	}

	public Notification(java.lang.String id, java.lang.String attr1,
			java.lang.String attr2, java.lang.String attr3,
			java.lang.String attr4, java.lang.String attr5) {
		this.id = id;
		this.attr1 = attr1;
		this.attr2 = attr2;
		this.attr3 = attr3;
		this.attr4 = attr4;
		this.attr5 = attr5;
	}

}